spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  main:
    allow-circular-references: true

comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png

