spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro
  messages:
    basename: i18n/messages
  main:
    allow-circular-references: true

server:
  port: 8080
comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png

